<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>testclient</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="ManagedBass">
        <HintPath>..\..\..\.nuget\packages\managedbass\4.0.2\lib\net8.0\ManagedBass.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Logging">
        <HintPath>..\..\..\.nuget\packages\microsoft.extensions.logging\10.0.0\lib\net9.0\Microsoft.Extensions.Logging.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.Extensions.Logging.Abstractions">
        <HintPath>..\..\..\.nuget\packages\microsoft.extensions.logging.abstractions\10.0.0\lib\net9.0\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\libs\OpenFreqAudio\OpenFreqAudio\OpenFreqAudio.csproj" />
      <ProjectReference Include="..\OpenFreq.Common\OpenFreq.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
    </ItemGroup>

</Project>
